/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TourTip {
        "order": number;
        "tipText": string;
    }
}
declare global {
    interface HTMLTourTipElement extends Components.TourTip, HTMLStencilElement {
    }
    var HTMLTourTipElement: {
        prototype: HTMLTourTipElement;
        new (): HTMLTourTipElement;
    };
    interface HTMLElementTagNameMap {
        "tour-tip": HTMLTourTipElement;
    }
}
declare namespace LocalJSX {
    interface TourTip {
        "order"?: number;
        "tipText"?: string;
    }
    interface IntrinsicElements {
        "tour-tip": TourTip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tour-tip": LocalJSX.TourTip & JSXBase.HTMLAttributes<HTMLTourTipElement>;
        }
    }
}
